[package]
name = "kreativity-ui-rs"
version = "0.1.0"
authors = ["Alexandru Pana <astronothing@gmail.com>"]

[dependencies.nanovg]
version = "0.3.0"
features = ["gl3"]

[dependencies.glfw]
git = "https://github.com/bjz/glfw-rs"

[dependencies.gl]
git = "https://github.com/bjz/gl-rs"
